#!/usr/bin/env python3
"""
Generated train-only entry-curve candidate.

Generated by analysis/autoresearch_kou/build_entry_curve_candidate.py.
Do not hand-edit this file; regenerate it when the training data changes.
"""

from __future__ import annotations

import math
from typing import Any, Mapping


CANDIDATE_NAME = "generated_entry_curve_roi_seek_v1"
CANDIDATE_DESCRIPTION = (
    "Train-only roi_seek entry caps with clean prior-60s regime filter. "
    "Generated at 2026-04-29T14:35:42Z."
)
TRAINING_SPLIT = {
    "20260421T202422Z": "train",
    "20260422T202134Z": "train",
    "20260423T164851Z": "train",
    "20260424T092134Z": "train",
    "20260424T175300Z": "train",
    "20260427T092525Z": "train",
    "20260427T141724Z": "validation",
    "20260427T185610Z": "validation",
    "20260428T060825Z": "test",
    "20260428T133101Z": "test",
    "20260429T060822Z": "test"
}
ENTRY_CAPS = {
    "eth": {
        "no": {
            "0.90": 1.0,
            "0.91": 1.0,
            "0.92": 0.94,
            "0.93": 1.0,
            "0.94": 0.96,
            "0.95": 0.96,
            "0.96": 1.0
        },
        "yes": {
            "0.90": 1.0,
            "0.91": 1.0,
            "0.92": 1.0,
            "0.93": 1.0,
            "0.94": 1.0,
            "0.95": 1.0,
            "0.96": 1.0
        }
    },
    "xrp": {
        "no": {
            "0.90": 0.94,
            "0.91": 0.94,
            "0.92": 0.96,
            "0.93": 0.96,
            "0.94": 0.96,
            "0.95": 0.96,
            "0.96": 0.99
        },
        "yes": {
            "0.90": 0.94,
            "0.91": 0.94,
            "0.92": 0.94,
            "0.93": 0.96,
            "0.94": 0.96,
            "0.95": 0.99,
            "0.96": 0.99
        }
    }
}


def _float(value: Any, default: float | None = None) -> float | None:
    try:
        if value is None:
            return default
        number = float(value)
    except (TypeError, ValueError):
        return default
    return default if math.isnan(number) or math.isinf(number) else number


def _entry_cap(asset: str, side: str, threshold: float | None) -> float:
    threshold_key = f"{0.90 if threshold is None else round(float(threshold), 2):.2f}"
    return ENTRY_CAPS.get(asset, {}).get(side, {}).get(threshold_key, 1.0)


def score_first_signal(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "allow_trade": True,
        "adjusted_prob_yes": _float(row.get("kou_yes"), _float(row.get("bs_yes"))),
        "reason": "first_signal_unchanged",
    }


def score_grid_event(row: Mapping[str, Any]) -> dict[str, Any]:
    asset = str(row.get("asset") or "").lower()
    side = str(row.get("side") or "").lower()
    threshold = _float(row.get("threshold"), 0.90)
    adverse_60s = _float(row.get("path_60s_adverse_share"), 0.0)
    z_change_60s = _float(row.get("path_60s_margin_z_change"), 999.0)
    time_left = _float(row.get("time_left_s"), 999.0)
    entry_price = _float(row.get("entry_price"))

    if time_left is not None and time_left < 5.0:
        return {"allow_trade": False, "reason": "too_late_execution_risk"}

    if adverse_60s is not None and adverse_60s > 0.05:
        return {"allow_trade": False, "reason": "prior_60s_adverse_exposure"}

    if z_change_60s is not None and z_change_60s < 1.0:
        return {"allow_trade": False, "reason": "weak_prior_60s_margin_improvement"}

    cap = _entry_cap(asset, side, threshold)
    if entry_price is not None and entry_price > cap:
        return {"allow_trade": False, "reason": f"entry_price_above_{cap:.2f}"}

    return {"allow_trade": True, "reason": "clean_path_generated_entry_curve"}
